# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/LAB4/Databricks/Lab5/Lab5_Bundle/src/Lab5PipelineJoshua")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM workspace.josurekamotho.sample_aggregation_lab5pipelinejoshua"))

# COMMAND ----------

import requests
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    StructType, StructField, StringType, DoubleType, LongType, BooleanType
)
from datetime import datetime, timezone
from pyspark.sql.functions import current_timestamp

# Initialize Spark session
spark = SparkSession.builder.getOrCreate()

# 1. Fetch data from OpenSky REST API
url = "https://opensky-network.org/api/states/all"
response = requests.get(url, timeout=30)

if response.status_code == 200:
    data = response.json()
    states = data.get("states", [])
    
    # Fixed deprecation warning using timezone-aware UTC datetime
    timestamp = data.get("time", int(datetime.now(timezone.utc).timestamp()))
    
    if states:
        schema = StructType([
            StructField("icao24", StringType(), True),
            StructField("callsign", StringType(), True),
            StructField("origin_country", StringType(), True),
            StructField("time_position", LongType(), True),
            StructField("last_contact", LongType(), True),
            StructField("longitude", DoubleType(), True),
            StructField("latitude", DoubleType(), True),
            StructField("baro_altitude", DoubleType(), True),
            StructField("on_ground", BooleanType(), True),
            StructField("velocity", DoubleType(), True),
            StructField("true_track", DoubleType(), True),
            StructField("vertical_rate", DoubleType(), True),
            StructField("sensors", StringType(), True),
            StructField("geo_altitude", DoubleType(), True),
            StructField("squawk", StringType(), True),
            StructField("spi", BooleanType(), True),
            StructField("position_source", LongType(), True)
        ])

        cleaned_states = [row[:17] for row in states if row is not None]
        df = spark.createDataFrame(cleaned_states, schema=schema)
        
        df_bronze = df.withColumn("ingestion_timestamp", current_timestamp())

        # Safely fall back to default catalog/schema if running interactively in a notebook
        try:
            catalog = spark.conf.get("spark.databricks.workspace.catalog")
        except Exception:
            catalog = "workspace"  # Default fallback for testing

        try:
            bronze_schema = spark.conf.get("spark.databricks.workspace.schema")
        except Exception:
            bronze_schema = "default"  # Default fallback for testing

        table_name = f"{catalog}.{bronze_schema}.bronze_opensky_flights"

        # Write to Bronze Delta table (Append mode)
        df_bronze.write \
            .format("delta") \
            .mode("append") \
            .saveAsTable(table_name)
            
        print(f"Successfully ingested {len(cleaned_states)} records into {table_name}")
    else:
        print("No flight state data returned from OpenSky API.")
else:
    print(f"Failed to fetch OpenSky data. Status code: {response.status_code}")

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM workspace.default.bronze_opensky_flights limit 10 ;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT DISTINCT position_source, count(*) 
# MAGIC FROM workspace.default.bronze_opensky_flights group by position_source ;

# COMMAND ----------

import requests
import logging
from datetime import datetime, timezone
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    StructType, StructField, StringType, DoubleType, LongType, BooleanType
)
from pyspark.sql.functions import current_timestamp

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("OpenSkyIngestion")

def ingest_opensky_data():
    spark = SparkSession.builder.getOrCreate()

    # 1. Fetch data from OpenSky REST API with timeout
    url = "https://opensky-network.org/api/states/all"
    logger.info(f"Fetching data from OpenSky API: {url}")
    
    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to connect to OpenSky API: {e}")
        raise

    data = response.json()
    states = data.get("states", [])
    
    if not states:
        logger.warning("No flight state data returned from OpenSky API.")
        return

    # 2. Define schema matching OpenSky state vector fields
    schema = StructType([
        StructField("icao24", StringType(), True),
        StructField("callsign", StringType(), True),
        StructField("origin_country", StringType(), True),
        StructField("time_position", LongType(), True),
        StructField("last_contact", LongType(), True),
        StructField("longitude", DoubleType(), True),
        StructField("latitude", DoubleType(), True),
        StructField("baro_altitude", DoubleType(), True),
        StructField("on_ground", BooleanType(), True),
        StructField("velocity", DoubleType(), True),
        StructField("true_track", DoubleType(), True),
        StructField("vertical_rate", DoubleType(), True),
        StructField("sensors", StringType(), True),
        StructField("geo_altitude", DoubleType(), True),
        StructField("squawk", StringType(), True),
        StructField("spi", BooleanType(), True),
        StructField("position_source", LongType(), True)
    ])

    # Clean and truncate rows to match the 17 expected columns
    cleaned_states = [row[:17] for row in states if row is not None]

    # 3. Create Spark DataFrame and add ingestion timestamp
    df = spark.createDataFrame(cleaned_states, schema=schema)
    df_bronze = df.withColumn("ingestion_timestamp", current_timestamp())

    # 4. Resolve target Catalog and Schema dynamically
    # Try to read from job config (when running as part of opensky_workflow)
    # Fall back to defaults for interactive notebook exploration
    try:
        catalog = spark.conf.get("spark.lab5.catalog")
    except Exception:
        catalog = "workspace"  # Default for serverless/interactive use
    
    try:
        bronze_schema = spark.conf.get("spark.lab5.bronze_schema")
    except Exception:
        bronze_schema = "lab5_bronze"  # Default for serverless/interactive use
    print("Catalog is ", catalog)
    print("Schema is ", bronze_schema)
    table_name = f"{catalog}.{bronze_schema}.bronze_opensky_flights"
    print("Table name is ", table_name)
    # Ensure schema exists before writing
    spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{bronze_schema}")
    
    table_name = f"{catalog}.{bronze_schema}.bronze_opensky_flights"

    # 5. Write to Bronze Delta table (Append mode)
    logger.info(f"Writing {len(cleaned_states)} records to Delta table: {table_name}")
    display(df_bronze)
    df_bronze.write \
        .format("delta") \
        .mode("append") \
        .saveAsTable(table_name)
        
    logger.info("OpenSky ingestion completed successfully.")

if __name__ == "__main__":
    ingest_opensky_data()


# COMMAND ----------

# MAGIC %sql
# MAGIC select * from workspace.default.bronze_opensky_flights limit 10;

# COMMAND ----------

